# A demo custom resource for the Kopf example operators.
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: global-secret2
matchNamespace:
  - 'cluster.*'
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
