apiVersion: v2
name: cluster-secret
description: ClusterSecret Operator
kubeVersion: '>= 1.16.0-0'
type: application
version: 0.1.0
sources:
- https://github.com/zakkg3/ClusterSecret
appVersion: "0.8.0"
