name: E2E Testing

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true
          cache: 'pip' # caching pip dependencies

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Build Docker Image
        run: docker build -t cluster-secret:${{ github.sha }} .

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Loading locally build image to kind cluster
        run: kind load docker-image cluster-secret:${{ github.sha }} --name=chart-testing

      - name: Run helm install
        run: helm install cluster-secret ./charts/cluster-secret -n cluster-secret --create-namespace --set clustersecret.clustersecret.image.repository=cluster-secret,clustersecret.clustersecret.image.tag=${{ github.sha }}

      - run: pip3 install -r conformance/requirements.txt
        name: Install python requirements

      - name: Run testing
        run: python3 conformance/tests.py
