# Docker build images on tag
name: Build and Push Image
on:
  push:
    tags:
      - '*'
#          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
#          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

env:
  IMAGE_TAGS: latest ${{ github.sha }} ${{  github.ref_name }}
  REGISTRY_USER: clustersecret
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE : clustersecret
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  
  login:
    name: Log in to image registry
    runs-on: ubuntu-20.04
    steps:
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: clustersecret
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: quay.io/clustersecret

  build-push-quay:
    name: Build and push manifest
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true ]
        # install_latest: [ true, false ]

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Install latest podman
        if: matrix.install_latest
        run: |
          bash .github/install_latest_podman.sh

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static


      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAMESPACE }}
          tags: ${{ env.IMAGE_TAGS }}
          archs: , 
          platforms: linux/386, linux/amd64, linux/arm64, linux/ppc64le, linux/s390x, linux/arm/v5, linux/arm/v7, linux/arm64/v8
          containerfiles: |
            ./Dockerfile.gh

      # Push the image manifest to Quay.io (Image Registry)
      - name: Push To Quay
        uses: ./
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
          # username: ${{ secrets.REGISTRY_USER }}
          # password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
